pipeline:
  name: sdfsdafsaf
  identifier: sdfsdafsaf
  projectIdentifier: development
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: one
        identifier: one
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: one
                  identifier: one
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "<+pipeline.stages.one.variables.one>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        variables:
          - name: one
            type: String
            description: ""
            value: <+pipeline.startTs>
    - stage:
        name: two
        identifier: two
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: two
                  identifier: two
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "<+pipeline.stages.one.variables.one>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  delegateSelectors:
    - ecs
