apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.app }}
    tt: {{ .Values.tt }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: web
        image: {{ .Values.image }}
        ports:
        - containerPort: {{int .Values.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{int .Values.port }}
