name: <+service.name>-<+stage.spec.infrastructure.environmentRef>
app: <+service.name>
image: <+artifact.image>
port: <+stage.spec.serviceConfig.serviceDefinition.spec.variables.port>
replicas: <+stage.spec.serviceConfig.serviceDefinition.spec.variables.replicas>
